[package]
name = "concacti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
globset = "0.4.14"
tempfile = "3.10.1"
termtree = "0.4.1"
