name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  build_and_release:
    name: Build and Release
    needs: build_and_test
    if: github.event_name == 'release' && github.event.action == 'created'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-13-large
            target: x86_64-apple-darwin
          - os: macos-13-large
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Rename binary
        run: |
          mv target/${{ matrix.target }}/release/file_concatenator \
             file_concatenator-${{ github.ref_name }}-${{ matrix.target }}
      - name: Generate checksum
        run: |
          sha256sum file_concatenator-${{ github.ref_name }}-${{ matrix.target }} > \
            file_concatenator-${{ github.ref_name }}-${{ matrix.target }}.sha256
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./file_concatenator-${{ github.ref_name }}-${{ matrix.target }}
          asset_name: file_concatenator-${{ github.ref_name }}-${{ matrix.target }}
          asset_content_type: application/octet-stream
      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./file_concatenator-${{ github.ref_name }}-${{ matrix.target }}.sha256
          asset_name: file_concatenator-${{ github.ref_name }}-${{ matrix.target }}.sha256
          asset_content_type: text/plain
