name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout homebrew-concacti
      uses: actions/checkout@v2
      with:
        repository: stargazing-dino/homebrew-concacti
        token: ${{ secrets.PAT }}
        path: homebrew-concacti

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Update Formula
      run: |
        VERSION=${{ github.event.release.tag_name }}
        VERSION_NUMBER=${VERSION#v}
        
        # Update for aarch64
        AARCH64_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/concacti-${VERSION}-aarch64-apple-darwin"
        AARCH64_SHA=$(curl -sL ${AARCH64_URL} | shasum -a 256 | cut -d ' ' -f 1)
        
        # Update for x86_64
        X86_64_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/concacti-${VERSION}-x86_64-apple-darwin"
        X86_64_SHA=$(curl -sL ${X86_64_URL} | shasum -a 256 | cut -d ' ' -f 1)
        
        sed -i "s/version \".*\"/version \"${VERSION_NUMBER}\"/" homebrew-concacti/Formula/concacti.rb
        sed -i "s|url \".*-aarch64-apple-darwin\"|url \"${AARCH64_URL}\"|" homebrew-concacti/Formula/concacti.rb
        sed -i "s/sha256 \".*\" # aarch64/sha256 \"${AARCH64_SHA}\" # aarch64/" homebrew-concacti/Formula/concacti.rb
        sed -i "s|url \".*-x86_64-apple-darwin\"|url \"${X86_64_URL}\"|" homebrew-concacti/Formula/concacti.rb
        sed -i "s/sha256 \".*\" # x86_64/sha256 \"${X86_64_SHA}\" # x86_64/" homebrew-concacti/Formula/concacti.rb

    - name: Commit and Push Changes
      run: |
        cd homebrew-concacti
        git add Formula/concacti.rb
        git commit -m "Update formula to ${{ github.event.release.tag_name }}"
        git push